Updating Maven version since AppVeyor started throwing errors:
```
Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
refreshenv
Reading environment variables from registry. Please wait... Done.
mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
Error: M2_HOME is set to an invalid directory.
M2_HOME = "C:\bin\apache-maven-3.2.5"
Please set the M2_HOME variable in your environment to match the
location of the Maven installation
```